=== ramosfredson2004-sys/Mykumpanya/Desktop/IPT2-LAB-ACT/book.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="book">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="title" type="xs:string"/>
        <xs:element name="author" type="xs:string"/>
        <xs:element name="year" type="xs:gYear"/>
        <xs:element name="publisher">
          <xs:complexType>
          <xs:sequence>
              <xs:element name="name" type="xs:string"/>
              <xs:element name="country" type="xs:string"/>
              <xs:element name="founded" type="xs:gYear"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="id" type="xs:ID" use="required"/>
      <xs:attribute name="genre" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== ramosfredson2004-sys/Mykumpanya/Desktop/IPT2-LAB-ACT/book.xml
<?xml version="1.0"?>
<book xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="book.xsd"
id="b01" genre="fiction">

 <title>The Great Gatsby</title>
  <author>F. Scott Fitzgerald</author>
  <year>1925</year>
  <publisher>
    <name>Scribner</name>
    <country>USA</country>
    <founded>1846</founded>
  </publisher>
</book>
